# Generated by Django 5.2 on 2025-04-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_name_todolist_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='title',
            new_name='name',
        ),
    ]
