# Generated by Django 5.2 on 2025-04-17 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_tag_todoitem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('need_to_check', 'Need to check'), ('not_confirmed', 'Not confirmed'), ('confirmed', 'Confirmed')], default='need_to_check')),
                ('created_by', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('todo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todoitem')),
            ],
        ),
    ]
