# Generated by Django 5.2 on 2025-04-23 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_todoitem_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='assign',
            field=models.ManyToManyField(blank=True, related_name='assigned_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
